### ISSUE TITLE
Feature: lambda arm64v8

### ISSUE THREAD

**Issue by matthewnessworthy** [jcupitt/docker-builds#13]
AWS lambda now has arm64v8 support, any chance of building vips+sharp for this platform?

https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/?nc1=b_rp

**Comment by jcupitt** [comment]
Hi @matthewnessworthy, I don't use AWS arm64, so I wouldn't be able to develop or test this. Perhaps the sharp issue tracker would be a better place to ask?

**Comment by matthewnessworthy** [comment]
@jcupitt ok thanks
