### ISSUE TITLE
unable to run in aws lamda

### ISSUE THREAD

**Issue by sathishravula** [jcupitt/docker-builds#3]
vips: error while loading shared libraries: libvips.so.42: cannot open shared object file:

**Comment by jcupitt** [comment]
You'll need to give some more information! What are you trying to achieve, what did you do, what libvips version, what platform, etc. etc.

**Comment by sathishravula** [comment]
i used libvips-amazonlinux2 docker file with 8.8.1 version and extracted tar from /usr/local/vips.
i added created zip file it having 
       /lib
       /bin
       /include
       /share       
   later added to aws layer, this layer added to aws lamda .
  i am trying to excute the shell commands from python like (os.system('vips --version'), i am getting the error

**Comment by jcupitt** [comment]
I think you need to set `LD_LIBRARY_PATH` or configure `ld.so.conf`. This is an AWS question rather than anything about pyvips, so I would ask on their forum.
