### ISSUE TITLE
`vips text` renders as a tofu in Alpine Linux

### ISSUE THREAD

**Issue by Nakilon** [jcupitt/docker-builds#4]
See https://github.com/felixbuenemann/vips-alpine/issues/3#issuecomment-611335555
Since the problem also appears even when based on the Dockerfile from this repo I decided to create the Issue here.

**Comment by jcupitt** [comment]
Tofu means fontconfig couldn't find a font that satisfied the requirements.

It looks like alpine does not install any fonts by default. I added this and it seems to work:

```
RUN apk add \
        pango-dev \
        msttcorefonts-installer
RUN update-ms-fonts \
        && fc-cache -f
```

**Comment by Nakilon** [comment]
Thank you!
