### ISSUE TITLE
[Question] use poppler to work with sharp and PDFs

### ISSUE THREAD

**Issue by kobsTheReal** [jcupitt/docker-builds#5]
Thanks a lot for this library!
I'm pretty new to this so sorry by advance if the question is dumb.

I'm planning to use sharp with a custom build of libvips with poppler (as PDFium seems a bit tricky).
I've added the following to the docker build and it seems to work.

```
apt-get install software-properties-common
add-apt-repository -y ppa:cran/poppler
apt-get update
apt-get install -y libpoppler-cpp-dev
```

Is this sufficent? 
Many thanks!

**Comment by jcupitt** [comment]
Hello, I think you just need `apt install libvips-dev`.

It depends what platform you are using. Is this current stable ubuntu?

**Comment by kobsTheReal** [comment]
Thanks for your feedback!
Yes it should be the stable ubuntu 18 but when I run such command it give me 
```
The following packages have unmet dependencies:
 libvips-dev : Depends: libjpeg-dev
               Depends: libtiff-dev but it is not going to be installed
               Depends: libpng-dev but it is not going to be installed
               Depends: libmagickcore-dev but it is not going to be installed
               Depends: libmagickwand-dev but it is not going to be installed
               Depends: libfreetype6-dev but it is not going to be installed
               Depends: libpango1.0-dev but it is not going to be installed
               Depends: libfontconfig1-dev but it is not going to be installed
               Depends: libexif-gtk-dev but it is not going to be installed
               Depends: libmatio-dev but it is not going to be installed
               Depends: libpoppler-glib-dev but it is not going to be installed
               Depends: librsvg2-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I've been installing some packages in the past that seems to conflict.
No sure what to do next.
```
$ dmesg | head -1
[    0.000000] Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 (Ubuntu 4.15.0-29.31-generic 4.15.18)
```

**Comment by jcupitt** [comment]
18.04 is the previous stable Ubuntu, 20.04 is current stable, so you might be able to upgrade. The libvips in 20.04 is fine to use.

The libvips that comes with in 18.04 is very old. You should probably build your own libvips if you have to use that platform.

It looks like your packages have become a bit messed up. Perhaps an update was cancelled half-way? You'll need to fix your broken packages before you can go any further.

**Comment by kobsTheReal** [comment]
Thanks a lot for the help that has nothing to do with the actual lib!

**Comment by kobsTheReal** [comment]
Sorry to come back on this one, it looks I got libvips-dev installed ok on a 20.04 but sharp.format is still showing that pdf isn't ready. I'll see if I can get some help from lovell.
```
  pdf:
   { id: 'pdf',
     input: { file: false, buffer: false, stream: false },
     output: { file: false, buffer: false, stream: false } },
```

**Comment by jcupitt** [comment]
I think you'll need to wipe sharp and reinstall, did you do that? 

You can verify that your libvips has PDF support with:

```
$ vips pdfload
load PDF from file
usage:
   pdfload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   page         - Load this page from the file, input gint
			default: 0
			min: 0, max: 100000
... etc.
```

And also check that your libvips is the one that sharp sees (in case you have several libvipses installed).

**Comment by kobsTheReal** [comment]
Ok! I'll check that out!
Many thanks for the help!!

**Comment by kobsTheReal** [comment]
All good now, reinstalling did the job! Many thanks!
